### DISCUSSION TITLE
pool timed out while waiting for an open connection

### DISCUSSION THREAD

**Discussion by ac5tin** [TaKO8Ki/gobang#110] [Q&A] [answered]
i just installed gobang using `cargo install --version 0.1.0-alpha.4 gobang `

i've edited the `config.toml`
```toml
[[conn]]
type = "postgres"
user = "xxxxxxx"
host = "xxxxxxxxxx.us-east-1.rds.amazonaws.com"
port = 5432
database = "fastapg"
```

When i launch `gobang` and then select the connection i see the error.
![2021-09-15-163059_531x179_scrot](https://user-images.githubusercontent.com/24804667/133398578-36d81632-e90f-4f21-9be0-fee7b0f21ca6.png)
