### ISSUE TITLE
pool timed out while waiting for an open connection

### ISSUE THREAD

**Issue by TaKO8Ki** [TaKO8Ki/gobang#111]
### Discussed in https://github.com/TaKO8Ki/gobang/discussions/110

<div type='discussions-op-text'>

<sup>Originally posted by **ac5tin** September 15, 2021</sup>
i just installed gobang using `cargo install --version 0.1.0-alpha.4 gobang `

i've edited the `config.toml`
```toml
[[conn]]
type = "postgres"
user = "xxxxxxx"
host = "xxxxxxxxxx.us-east-1.rds.amazonaws.com"
port = 5432
database = "fastapg"
```

When i launch `gobang` and then select the connection i see the error.
![2021-09-15-163059_531x179_scrot](https://user-images.githubusercontent.com/24804667/133398578-36d81632-e90f-4f21-9be0-fee7b0f21ca6.png)
</div>
